name: CENTRESTAGENEWS
favicon: null
layout_spectrum: 0.4845848900731653
typography_spectrum: 0.9745767917484045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5149949891492724
  lightness: 0.432006174698472
  saturation: 0.9498192023020238
  rhythmicContrast: 0.262429925147444
purpose: []
