name: CSNEWS
favicon: null
layout_spectrum: 0.43108
typography_spectrum: 0.79958
title: 'NEWS & HAPPENINGS'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#333029'
    - '#a6a090'
    - '#c24510'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
